### PR TITLE
Added linux instructions to INSTALLING.md

### PR DESCRIPTION
**Pull request by hoovercj**
Since this isn't a code change, I've based this on master as I assume that's where these non-version specific docs should be.

### CODE REVIEW

**Comment by SoullessWaffle** [comment]
You raise a good point which I don't think we've discussed before.
In my opinion, general documentation changes should get pushed through to `master` ASAP.

However, if you open a PR directly to `master` then the changes don't appear on `develop`.
I do think we should be consistent in that every change should go through `develop` before it hits `master`, especially since `develop` is currently selected as the default branch on GitHub.

Perhaps we could then increment the [patch version][semver] and push the change to master straight away.
This also adheres to [Semver][semver] since we're not really adding functionality, and lack of proper documentation could be considered a bug :laughing: 

To summarize, I propose this workflow for general documentation changes on both [api] and [ui]:

1. Fork the repo
2. Create a feature branch  (e.g. `installing-linux`)
3. Commit your changes and push them to the feature branch
4. Send a pull request to the original repo with the `develop` branch as base and your feature branch as compare
5. Discussion happens, maybe some modifications are made to the PR
6. PR gets accepted or rejected
7. If accepted, the [patch][semver] version will be incremented in `package.json` and the change gets pushed through to `master`
8. At this point you can delete your feature branch (GitHub will offer to do this for you on the PR page)

@ericdouglas @oscar-g @waterlooSunset thoughts?

[semver]: http://semver.org/
[api]: https://github.com/open-source-society/ossu-api
[ui]: https://github.com/open-source-society/ossu-ui

**Comment by hoovercj** [comment]
patch versions shouldn't need to update for documentation changes though, should it?

**Comment by ericdouglas** [comment]
@SoullessWaffle I agree with all those steps, but we shouldn't patch versions for doc updates, just for new features, IMO.

**Comment by SoullessWaffle** [comment]
That works for me.

**Comment by oscar-g** [comment]
@hoovercj good work.

I think that each developer should be responsible for researching the installation procedures on their own.  That being said, your changes improve INSTALLING.md

I am willing to merge this in. However, please make a pull request to the 'develop' branch in order to maintain consistency in our workflow.

Thanks!

**Pull request closed without merging**
