### PR TITLE
Curriculum schema

### PR DESCRIPTION
**Pull request by waterlooSunset**
Reopen on develop branch...

### CODE REVIEW

**Comment by oscar-g** [comment]
@ericdouglas @waterlooSunset 
We should probably merge the categories schema into the curriculum schema:

```
{
    cat: [{
        name: String,
        courses: [ObjectId]
    }]
}
```

If we go even further, we could also merge the course schema into the curriculum schema

**Comment by waterlooSunset** [comment]
I think modeling the curricula and courses as different creates a more modular approach. We can create a course, say Calculus 1 and link it to multiple curricula without unnecessary duplication. There will likely be a lot of overlap between Computer Science and Computer Engineering, defining each course in each curricula doesn't seem DRY

**Comment by oscar-g** [comment]
Yeah, you're right and I agree, but we are using document storage and maintaining relations is a PITA...we'll deal with it on the application.  Anyhow, removing the category schema will alleviate a lot of the relationship headaches.

**Comment by waterlooSunset** [comment]
Yes, I agree with removing the category schema

**Comment by ericdouglas** [comment]
@waterlooSunset @oscar-g :+1: to remove category schema

**Comment by oscar-g** [comment]
I'll go ahead and do this

**Comment by ericdouglas** [comment]
GO :horse_racing: ! :joy:

**Comment by oscar-g** [comment]
Should be ready to merge

**Comment by ericdouglas** [comment]
@oscar-g LGTM :shipit:

**Pull request merged**
