### PR TITLE
Migrate profiles (import.js)

### PR DESCRIPTION
**Pull request by evanplaice**
Profile migration CLI tool

Scrapes profile data directly from OSSU-Computer-Science/issues via the GitHub API.
Saves data to a file, output to console, or migrate (WIP) directly into to the database.
Can also process offline dumps of profile data for testing/debugging.

Migrations support will be added in the future once the User schema is ready.

Dependencies:
- minimist - used to sanely parse complex CLI args

### CODE REVIEW

**Comment by oscar-g** [comment]
@evanplaice Great work. I want to wait for #35 
It won't affect your code very much.  I think the only thing you have to do is mode the `import.js` to the `helpers` folder and, please name it something like `profile-import`.

**Comment by oscar-g** [comment]
Can you tell me a little bit about the `Dump a sample issues.json`?
1) Does it extract user data from the registration issue?
2) can we add in the additional registration issues?

https://github.com/open-source-society/computer-science/issues/31
https://github.com/open-source-society/computer-science/issues/109
https://github.com/open-source-society/computer-science/issues/145

**Comment by evanplaice** [comment]
@oscar-g Sorry, this got closed prematurely. It closed automatically when I rebased onto the latest version of 'ossu-api/develop'.

To answer your questions:

**Renaming/moving issues.js:**
I'm planning to move/rename it to `/bin/utils.js` because it now runs as a CLI.

In addition, once the migration portion is complete I plan to merge in `connected.js' and 'collection.js'.

**Profile Dumps:**

1. Yes, it does extract data from the registration issues.

2. Yes, we can add additional registration issues. Which is part of the reason I refactored the code into a class. Migration requires multiple API requests and therefore multiple instance.

The 'dump a sample' does exactly what it says. Due to limitations baked into the GitHub API, only a limited number of records can be transmitted per request. Since the issues are so big, requests have to be paged.

The migration method will be responsible for pulling together the complete collection of profiles in one shot.

**Comment by oscar-g** [comment]
@evanplaice That's great, good work.

What will be the use case for `connected.js`?
Surely, a developer will know when the database isn't running.  The node server (index.js) yells at you when it can't connect.

I can see how `collection.js` is a useful CLI for managing things without the OSS-UI.  It would be nice if `collection.js` could expose a CLI interface to the files in `controllers` (see the PR, mentioned above).  That way, we won't have duplicate code or tests.

**Comment by evanplaice** [comment]
@oscar-g TBH, I wrote both because I'm new to MongoDB and was trying to get a feel for it.

connected.js - provides a simple pass/fail check on the DB from the CLI. For instance, once we've successfully deployed the first version to production we can focus on streamlining the process into a scripted one-click-deploy.

collection.js - I agree, the connector doesn't currently adapt to our controllers because it was written prior to the decision to use mongoose. That can be fixed once I'm finished with other higher priority tasks.

**Comment by oscar-g** [comment]
@evanplaice I don't think `connected` will be necessary for the following reasons:

When we deploy, we'll have services at the operating-system level that will maintain the database server running 'forever'.

In other words, OSS-API should not concern itself with making the database available..in development, this is the developer's responsibility and in production it is up to the linux service configuration to make the db available.

When we run `npm start` or `node index.js`, the console yells at you when the database is not connected and the routes will not work properly...mongoose provides 'hooks' for this (check the docs).  The api server assumes the db is ready and simply doesn't start if the db is not ready (this assumption is OK because our environment configuration will guarantee that the database daemon is running). (check the database helper file for more info on how the database is loaded)

As far as a scripted deployment, the simplest way will be to use a git post-receive hook that installs npm dependencies and simply runs `npm start` to start the server.  This is process will require very little interaction and will be triggered with a `git push`. We could also look into continuous integration strategies...if we go that route, database availability will be part of the integration strategy, not the server code.

Please let me know if this makes sense.  I don't want us to misplace our efforts with things we won't end up using.

Finally, we can integrate the controllers into collection.js at a later point, if you don't want to do it right now.

**Comment by evanplaice** [comment]
@oscar-g No biggie, connection.js can be dropped if it's not used.

Yes, I'm planning to revamp collection.js at a later date. A task already exists in v0.0.4 saying as much. I'll update it to reflect these changes.

**Pull request closed without merging**
