### PR TITLE
Structure Proposal

### PR DESCRIPTION
**Pull request by thebergamo**
New directories:
- Controllers
- Helpers
- bin

Just introducing the controllers directory for putting the controllers for consume in Api. And in Helpers an defining the instance the database(mongoose) and threat all the behavior in this file and many others minor changes.

### CODE REVIEW

**Comment by oscar-g** [comment]
Great work @thebergamo! I like the controller and model loader.

1) I think we should create an index.js that actually starts the server in bin/server. This repo is just an api server so it makes sense that the main function of the repo is in the index file. This will let us test the server file, individually. `server.js` should export an app (a server). `index.js` should run `server.js` and use the `listen` method to start the server.

2) We could probably just rename 'helpers' to 'lib' and move `server.js` in there.

3) We also need to make sure that any changes here will pass the current test suite. (it may take some rewriting of the 'api server' suite.

4) where do we use the npm module 'inflection'?

**Comment by thebergamo** [comment]
@oscar-g thanks for your comments. I'll fix then and rebase with the test suite in my PR.

1) No problem. I can move the code in the `bin/server.js` to export an App and start the server in an `index.js` file.

2) In this case, `helpers` is more semantic instead `lib` I think. Because the files are only Helpers to setup a stuff in the project.

3) I'm will double check in this point. Because when I started to develop this proposal, The repo not have tests yet.

4) When the `helpers/loader.js` loaded the files in a directory, we need to camelize the name of the files in the returned objects. Just because `name: user` is very ugly when I need to call the model or controller on our case. `name: User` is much more better. And inflection have a lot of other methods who can help us too.

Btw, I'll change based on your proposal, and after that, waiting for the new comments.

**Comment by oscar-g** [comment]
for #4, if it's a matter of it looking nice...just declare the models with CapitalCamelCase...this way we can drop inflection...it's a bit unnecessary if we only use it once. Furthermore, declaring the models with CapitalCamelCase is more consistent with the [mongo docs](http://mongoosejs.com/docs/models.html)

In the model:

` return mongoose.model('User', userSchema);`

**Comment by thebergamo** [comment]
@oscar-g fix the tests and style checks! You can see?

Well, about it, the real problem is the loader, read the name file not the mongoose schema.  And the problem is too in the controllers folder.

**Comment by oscar-g** [comment]
@thebergamo This is almost good to go...it's looking really good.

Maybe we can change the model file names and the model names to have CapitalCamelCase. We really don't need inflect and it's important that the app is a lean as possible.

One more thing thing, though: we want to export the app from `server.js` and we want to use that file in the tests (index.js is the app entry point, we won't need to test that).


index.js should really just be: Import server, run the listen method.

server.js should take care of loading all the routes (including the api router `app.use('/api', Api(app))`). 

Don't worry about wrapping the listen method around the `db['database'].once('connected')`
If the database fails to connect, we'll know about it and it's the developer's responsibility to start the database.  This is a reasonable assumption, for the sake of writing code that can be tested.

Let me know if that makes sense

**Comment by ericdouglas** [comment]
@thebergamo I agree with @oscar-g , it's looking good!

My only concern is about the `klass` property name.

> "IMHO, this is a very bad idea. Reserved words are reserved for a reason, and doing this does decrease readability."

**Comment by thebergamo** [comment]
@ericdouglas and @oscar-g done =D

**Comment by ericdouglas** [comment]
@thebergamo :+1: :smile:

**Comment by oscar-g** [comment]
@thebergamo This still needs some work:

* Please update the model file names and the model name to be CapitalCamelCase
`User.js` and `model('User')`
* Remove the `inflect` dependency
* Revert the changes in `models/user.js` around lines 45-61 (these lines were commented out on purpose and we will use them later)


Also, quick question: why did you change the tests to use `expect`? They were already working with `assert`...

We need to make sure any changes are carried out for actual reasons based on the software, not personal preference (remember we're working together).  If something already works, let's not try to 'fix' it.

**Comment by thebergamo** [comment]
@oscar-g I got!

- CapitalCameCase in files are a bad, file just be named in lower case and if have two words in name, split using '-'(dash). So `model/user.js` I'll maintain in lower case. and the exported model I will change to CamelCase.
- I really think I remove the `inflection` but I'll revise it!
- I think commented code only pollutes the file at all, so I ended up taking. But I will put back the code.

About `assert`and `expect`I just change because, when we use expect when we read the tests, `expect` can be more intuitive about `whats going on here` but it's not an problem, and I can rollback this. =D

If you are ok, about my consideration I can fix and push again!

**Comment by oscar-g** [comment]
@thebergamo

* Ok. I think the `package.json` and the `loader` file are missing the camelize dep (https://www.npmjs.com/package/camelize).  That sounds good...let's keep the file name lower-dash-case and the model UpperCamelCase.
* If we need to use inflection for other things, we can add it in, but for now, just camelize.
* No need to worry about having perfect code right now because the project is changing constantly.  When we get to the release candidate stage, we'll clean it all up!

I agree `expect` is easier to follow.

As always, good work! :sake: :smile: 

Let's get this merged in so we can focus on `v0.0.3`

**Comment by oscar-g** [comment]
Merging this to move the project along.

We will need to fix fix the issues above, at some point.

**Pull request merged**
