### PR TITLE
User schema

### PR DESCRIPTION
**Pull request by waterlooSunset**
Reopen pull request for develop branch.

### CODE REVIEW

**Comment by oscar-g** [comment]
A few comments on the user schema:

First, we don't need to prefix key names with 'user_' because it is implied that these object keys are part of the user document.

Second, I think the curriculum could be modeled like this:
````
user_curriculum: {
    id: 'ObjectId' //id of a document that belongs to the 'curriculum' model
    started: 'Date' //when they started the curriculum 

    progress: [ {
        course_id: 'ObjectId' //id of a 'course' model 
        started: 'Date' //when they started the course
        status: String //'completed' or 'in-progress'

    } ]
}
````

Finally, let's model the `user_sites` in the way similar as what is described in the comment.  Let's go for simplicity here (no full urls, let the front end deal building the urls):
````
github: String, //the github handle
twitter: String, //the twitter handle
facebook: String //the facebook page handle
````

**Comment by ericdouglas** [comment]
Nice! You're doing great, just some points:

- ES5 instead of ES2015
- code isn't in the camelCase style
- name of the file: `models/userSchema.js` should be `models/user.js`. Everything inside the models folder will be a schema.
- different code style: `app.set('db', db);` and `app.use( '/api', Api(app) );` (spaces)

**Comment by oscar-g** [comment]
Also, let's write our model files so that they register and return the model on the default exports method

```
module.exports = function(){
  var userSchema = mongoose.schema({...});

  return mongoose.model('user', userSchema);
}

**Comment by oscar-g** [comment]
Looks great, @waterlooSunset 

I moved some properties into the 'acount' key.

**Comment by oscar-g** [comment]
This almost looks done, for now.
We'll need to think about how to best model the 'location', before merging into dev.

In the future, we'll to add method to create and destroy an authenticated session. I'll look into the auth strategy tomorrow.

**Comment by waterlooSunset** [comment]
@oscar-g Big thanks, looks much cleaner.

**Comment by ericdouglas** [comment]
- About the course default status, we need 3 status, `not-started`, `in-progress` and `done`. The default status should be `not-started`.
- Needs a space after `true` [here](https://github.com/open-source-society/ossu-api/blob/8c2036d0eab6c17f8ad32d50cf5a70c6b81cf548/models/user.js#L38)
- Everything else LGTM :+1: 

Nice job! :wink:

**Comment by oscar-g** [comment]
@ericdouglas 
Regarding the course status.  I actually think we don't need a `status` property...only a Boolean `completed` property.  There is a more efficient way to model course progress.

For example, when the user signs up for the curriculum, the model looks like:
```
user: {
    fname: 'Oscar',
    curriculum: [ { 
        id: curriculum_id,
        progress: [ ]
    } ]
}
```

Notice that the progress array is empty because they haven't started any courses.

The front end should query an api like `/curriculum/:id` which will return the details along with an array of courses in that curriculum; the front end should infer that, because the `progress` array is empty, then the user has not started any courses.

When the user adds a course, the user model looks like:
```
user: {
    fname: 'Oscar',
    curriculum: [ { 
        id: curriculum_id,
        progress: [ {
            id: course_id,
            started: Date.now
            completed: false
        } ]
    } ]
}
```

The object above represents the 'in-progress' state for the course with course_id.

When the user completes the course we set the `completed` flag to `true`.

This way of modeling the curriculum progress is more effective because it does not store string values that are basically arbitrary labels.  Keeping with the separation of concerns, the front-end is now responsible for interpreting the data correctly. This will keep our models very light.

Let me know if that makes sense.

**Comment by ericdouglas** [comment]
@oscar-g great solution! Totally agree :+1:

**Comment by oscar-g** [comment]
I'll implement that and commit to dev

**Pull request merged**
