### PR TITLE
Streamlined and consolidated markdown docs

### PR DESCRIPTION
**Pull request by hoovercj**
Streamlined the content from `INSTALLING.md` and moved it into `README.md`

### CODE REVIEW

**Comment by evanplaice** [comment]
@hoovercj you should rollback the last.

Instead use `git rebase upstream/develop`. To keep the history clean merging (ie `develop` into `master`) only takes place during a release.

I added some revision comments to the source. We should probably remove the mention of `connected.js` and `collection.js` since they were removed with the last release. I'm planning to combine the functionality of those with `migrate-profiles` into a `/bin/utils.js` later.

Thanks for taking care of that.

**Comment by hoovercj** [comment]
regarding `collection.js` and `connected.js`, they aren't mentioned at all. They should be deleted with the rest of `INSTALLING.md`

**Comment by evanplaice** [comment]
@hoovercj Cool.

One last thing, we should probably add a link to the API documentation in `README.md`:
http://open-source-society.github.io/ossu-api/docs/index.html

**Comment by evanplaice** [comment]
LGTM :+1:

**Pull request merged**
