### PR TITLE
added redis and passport dependencies to package.json for github logi…

### PR DESCRIPTION
**Pull request by waterlooSunset**
…n strategy

### CODE REVIEW

**Comment by SoullessWaffle** [comment]
Do we need redis for OAuth? Can't this be done using just MongoDB?

**Comment by waterlooSunset** [comment]
Yes, I think it can, Oscar suggested using Redis store to maintain sessions on the dev board.

**Comment by ericdouglas** [comment]
:+1:

**Comment by waterlooSunset** [comment]
I reopened this pull request on the develop branch. I should have known not to open on master.

thanks

**Comment by ericdouglas** [comment]
@waterlooSunset no problem :smile:

**Pull request closed without merging**
