### PR TITLE
Discussion time!

### PR DESCRIPTION
**Pull request by waterlooSunset**
started to workout a curriculum schema, trying to use the style of the current state of user.js, please let me know if 'm doing it wrong.

### CODE REVIEW

**Comment by oscar-g** [comment]
Looks great!

@ericdouglas what do you think of the category, should it be its own schema?

We could just have this
```
curriculum = {
    id: 12345
    categories: [{
        name: 'Intro to Comp Sci',
        courses: [{
            id: 12345 //'intro to comp sci'
        }, {
            id: 67890 //'intro to python'
        }]
    }, {
        name: 'Math',
        courses: [...]
    }]
}
````

**Comment by waterlooSunset** [comment]
Yeah! I wasn't sure it was necessary either.

**Comment by oscar-g** [comment]
Before we merge: close this and reopen the pull request against the develop branch, not the master branch.


Also, I'm having trouble writing tests again the model.statics.createModel methods (like in the user model the createUser method)...it looks like the method expects an instance of the model. An instance of the model would already have the `save` method (see mongoose docs), so it's kind of an anti-pattern to write a static method that requires an instance of the class.
Perhaps, we want to be able modify the model before saving? In that case we should use mongoose [middlewares](http://mongoosejs.com/docs/middleware.html)

**Comment by waterlooSunset** [comment]
I thought I had! Doing now

**Pull request closed without merging**
